### ISSUE TITLE
Fullstop between badges

### ISSUE THREAD

**Issue by PeopleInside** [justoverclockl/flarum-ext-welcomebox#13]
Can fullstop be resolved?
A black fullstop is present between the badges

![Immagine 2022-02-23 210957](https://user-images.githubusercontent.com/5006150/155400186-8c95a820-3a30-44b6-b2f3-41dc122d77f2.png)
![Immagine 2022-02-23 211019](https://user-images.githubusercontent.com/5006150/155400195-6087f6c4-83e0-412d-849b-7537446dda90.png)

I have the widget placed on left side instead of right side as in Flarum IT

The screen is taken from Edge that show the issue more than Firefox.

If the badge is one seems the fullstop is not present

![Immagine 2022-02-23 211347](https://user-images.githubusercontent.com/5006150/155400603-9093b5db-a80e-4fe2-9f73-bbfd6adfb208.png)

This issue should be caused by forum widgets?
https://github.com/afrux/forum-widgets-core

I added in Flarum CSS

```
/* Fix badge list welcomebox */

body {
	list-style: none;
}
```
I don't know if this will cause other issues on my forum.

**Comment by justoverclockl** [comment]
Let me take a look at this today

**Comment by justoverclockl** [comment]
can you try now with latest version?

**Comment by PeopleInside** [comment]
Seems resolved, thanks!
