### ISSUE TITLE
feature Request: Right side

### ISSUE THREAD

**Issue by Spooonky** [justoverclockl/flarum-ext-welcomebox#2]
Hey, can you add a switch so you can put the welcome box on the right side?

**Comment by justoverclockl** [comment]
can u explain better? you need to put ONLY the welcome box to the right? or u want all the left sidebar to the right?
because if u want to move the sidebar to right u can simply add this to your custom CSS:

```
.sideNav{
  margin-left: 50px;
  order: 1;
}
```

**Comment by Spooonky** [comment]
No, not the sidebar, just the WelcomeBox on the right side

**Comment by justoverclockl** [comment]
Not possible , this will ruin forum appearance
